server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:zz.git #git地址
        ####搜索目录
          search-paths:
            - springcloud-config
      label: master

eureka:
  #instance:
  #  hostname: cloud-gateway-service
  client:
    #register-with-eureka: true
    #fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka