server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false
    fetch-register: false
    service-url:
      defaultZone: http://localhost:7001/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
