server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-register: false
    service-url:
      defaultZone: http://localhost:7002/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
